"""first migration using alembic

Revision ID: a505d743d2ac
Revises: 
Create Date: 2021-08-10 15:32:27.815705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a505d743d2ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('match', sa.String(length=255), nullable=False),
        sa.Column('match_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('league', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet9jaodds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('match', sa.Integer(), nullable=True),
        sa.Column('home', sa.String(length=5), nullable=False),
        sa.Column('draw', sa.String(length=5), nullable=False),
        sa.Column('away', sa.String(length=5), nullable=False),
        sa.Column('home_or_away', sa.String(length=5), nullable=False),
        sa.Column('home_or_draw', sa.String(length=5), nullable=False),
        sa.Column('draw_or_away', sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(['match'], ['matches.id'], name='fk_bet9jaodds_matches_id_match'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betkingodds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('match', sa.Integer(), nullable=True),
        sa.Column('home', sa.Float(), nullable=False),
        sa.Column('draw', sa.Float(), nullable=False),
        sa.Column('away', sa.Float(), nullable=False),
        sa.Column('home_or_away', sa.Float(), nullable=False),
        sa.Column('home_or_draw', sa.Float(), nullable=False),
        sa.Column('draw_or_away', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['match'], ['matches.id'], name='fk_betkingodds_matches_id_match'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nairabetodds',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('match', sa.Integer(), nullable=True),
        sa.Column('home', sa.Float(), nullable=False),
        sa.Column('draw', sa.Float(), nullable=False),
        sa.Column('away', sa.Float(), nullable=False),
        sa.Column('home_or_away', sa.Float(), nullable=False),
        sa.Column('home_or_draw', sa.Float(), nullable=False),
        sa.Column('draw_or_away', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['match'], ['matches.id'], name='fk_nairabetodds_matches_id_match'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nairabetodds')
    op.drop_table('betkingodds')
    op.drop_table('bet9jaodds')
    op.drop_table('matches')
    # ### end Alembic commands ###
