name: deploy-py-lambda
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Deploy code to Lambda
        uses: jayteealao/py-lambda-action@layer_onlyv3
        with:
          lambda_layer_arn: "arn:aws:lambda:us-east-2:760141912310:layer:bevtestlayer"
          lambda_function_name: "bevtest"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
